#!/bin/sh

make html
cp -r ./_build/html/* ../
cp -r ./images/detailed_devel_sw_stack.svg  ../_images/
cp -r ./images/detailed_run_time_sw_stack.svg ../_images/
cp -r ./images/simplified_devel_sw_stack.svg ../_images/
cp -r ./images/simplified_run_time_sw_stack.svg ../_images/
cd ..
ln -s ./workflow/workflow.html workflow.html
