#!/bin/bash

cd images
convert workflow_types.svg                workflow_types.png
convert workflow_interfaces.svg           workflow_interfaces.png
convert conceptual_devel_sw_stack.svg     conceptual_devel_sw_stack.png
convert conceptual_run_time_sw_stack.svg  conceptual_run_time_sw_stack.png
convert detailed_devel_sw_stack.svg	  detailed_devel_sw_stack.png
convert detailed_run_time_sw_stack.svg	  detailed_run_time_sw_stack.png
convert simplified_devel_sw_stack.svg	  simplified_devel_sw_stack.png
convert simplified_run_time_sw_stack.svg  simplified_run_time_sw_stack.png
cd ..
make latexpdf
